version: "3"

networks:
  datamanager-dev:

volumes:
  db-data:

services:
  mysql:
    image: mysql:5.7
    networks:
      - datamanager-dev
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456 # 设置 Mysql root 用户密码
    ports:
      - "3306:3306"

  postgres:
    image: postgres:14-alpine
    networks:
      - datamanager-dev
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    networks:
      - datamanager-dev
    deploy:
      replicas: 1
      # update_config:
      #   parallelism: 2
      #   delay: 10s
      restart_policy:
        condition: on-failure
    entrypoint:
      - "redis-server"
      - "/etc/redis/redis.conf"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
